

BASE_URL = 'https://statsapi.web.nhl.com/api/v1'

TEAMS = {
    'NJD': 1,
    'NYI': 2,
    'NYR': 3,
    'PHI': 4,
    'PIT': 5,
    'BOS': 6,
    'BUF': 7,
    'MTL': 8,
    'OTT': 9,
    'TOR': 10,
    'ATL': 11,
    'CAR': 12,
    'FLA': 13,
    'TBL': 14,
    'WSH': 15,
    'CHI': 16,
    'DET': 17,
    'NSH': 18,
    'STL': 19,
    'CGY': 20,
    'COL': 21,
    'EDM': 22,
    'VAN': 23,
    'ANA': 24,
    'DAL': 25,
    'LAK': 26,
    'PHX': 27,
    'SJS': 28,
    'CBJ': 29,
    'MIN': 30,
    'MNS': 31,
    'QUE': 32,
    'HFD': 34,
    'CLR': 35,
    'HAM': 37,
    'PIR': 38,
    'QUA': 39,
    'DCG': 40,
    'MWN': 41,
    'QBD': 42,
    'MMR': 43,
    'NYA': 44,
    'SLE': 45,
    'OAK': 46,
    'AFM': 47,
    'KCS': 48,
    'CLE': 49,
    'DFL': 50,
    'BRK': 51,
    'WPG': 52,
    'ARI': 53,
    'VGK': 54,
    'SEA': 55
}

AWARDS = {
    'Stanley Cup': 1,
    'Jack Adams Award': 2,
    'Lady Byng Memorial Trophy': 3,
    'Calder Memorial Trophy': 4,
    'Clarence S. Campbell Bowl': 5,
    'King Clancy Memorial Trophy': 6,
    'Conn Smythe Trophy': 7,
    'Hart Memorial Trophy': 8,
    'William M. Jennings Trophy': 9,
    'Bill Masterton Memorial Trophy': 10,
    'James Norris Memorial Trophy': 11,
    'Lester Patrick Trophy': 12,
    'Ted Lindsay Award': 13,
    "Presidents' Trophy": 14,
    'Maurice Richard Trophy': 15,
    'Art Ross Trophy': 16,
    'Frank J. Selke Trophy': 17,
    'Vezina Trophy': 18,
    'Prince of Wales Trophy': 19,
    'NHL Lifetime Achievement Award': 20,
    'NHL Foundation Player Award': 21,
    'Mark Messier NHL Leadership Award': 22,
    'NHL General Manager of the Year Award': 23,
    'E.J. McGuire Award of Excellence': 24
}